### ISSUE TITLE
你好，我看了你的项目，觉得十分有意思

### ISSUE THREAD

**Issue by Minori-ty** [go-cqhttp/node#14]
请问你是否有意向做关于sauceNAO的搜图，和b站还有twitter的订阅推送插件？

**Comment by zhuweiyou** [comment]
暂时没有哦

**Comment by hbestm** [comment]
我看了这个redeme，还是没跑起来。go-cqhttp我是可以运行了。愚笨了。

**Comment by Minori-ty** [comment]
> 我看了这个redeme，还是没跑起来。go-cqhttp我是可以运行了。愚笨了。

在每个单独的插件里面也要npm i
