### ISSUE TITLE
调用股票查询会生成一个chrome进程，之后不会关闭，累积导致服务器宕机

### ISSUE THREAD

**Issue by jundaydev** [go-cqhttp/node#16]
调用股票查询会生成一个chrome进程，之后不会关闭，累积导致服务器宕机

**Comment by zhuweiyou** [comment]
https://github.com/go-cqhttp/node/blob/736bc2edb4a42a3bf2ea316a12740ebf9371e3ac/plugin/stock/service.js#L144

这边判断的是开发环境 不会关闭进程,  生产环境会close.
你是否使用 
https://github.com/go-cqhttp/node/blob/736bc2edb4a42a3bf2ea316a12740ebf9371e3ac/package.json#L5
跑在生产?

如果你没用pm2的话, 那你手动带 NODE_ENV=production 运行

因为开发为了方便调试 就没close看效果
