### ISSUE TITLE
大佬你好，提交一个BUG，当误启动2个npm run dev时，会创建2个webSocket

### ISSUE THREAD

**Issue by reimubaka** [go-cqhttp/node#3]
而如果关闭了SSH，那么就无法通过ctrl+c来关闭启动的服务，请问这个时候如何关闭。
PS：如果启动多个，那么BOT对于命令的回复就是多次，我尝试过杀端口，但每次启动webSocket会创建新的端口

**Comment by zhuweiyou** [comment]
对于 go-cqhttp 那边, 本身就允许多个 ws 连接的,  这不算是 bug.

如果在服务器上运行, 建议用 pm2, 先全局安装 pm2 模块, 然后:  `npm start`

https://github.com/go-cqhttp/node/blob/aa99c8e9cbf998fd5bda45acb6bce5e9badcb595/package.json#L3-L6


这样你哪怕退出了 SSH, 你的程序也在后台运行, 如果要关闭可以 `pm2 delete go-cqhttp-node`

**Comment by reimubaka** [comment]
我安装了pm2，使用了下,确实挺方便的。但由于关闭了ssh导致 npm run dev 启动的ws链接无法关闭了，请问这个如何关闭呢。
pm2 delete go-cqhttp-node 只能关闭npm start启动的ws连接

**Comment by zhuweiyou** [comment]
你可以尝试 `ps -ef | grep node`  找到带有 node 关键词的进程, 然后 `kill -9 PID` 杀掉

**Comment by reimubaka** [comment]
感谢大佬，已解决。我之前是用的lsof -i 来杀死端口的，结果发现不行。

**Comment by zhuweiyou** [comment]
不客气
